//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brenner.SilentCmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brenner.SilentCmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished &quot;{0}&quot;.
        /// </summary>
        internal static string FinishedCommand {
            get {
                return ResourceManager.GetString("FinishedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilentCMD.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting &quot;{0}&quot;.
        /// </summary>
        internal static string StartingCommand {
            get {
                return ResourceManager.GetString("StartingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilentCMD [BatchFile [BatchArguments]] [Options]
        ///
        ///Options:
        ////? :: Show help
        ////LOG:file :: Output status to LOG file (overwrite existing log).
        ////LOG+:file :: Output status to LOG file (append to existing log).
        ////DELAY:seconds :: Delay the execution of batch file by x seconds
        ///
        ///Examples
        ///SilentCMD c:\DoSomething.bat
        ///SilentCMD c:\MyBatch.cmd MyParam1 /LOG:c:\MyLog.txt
        ///SilentCMD c:\MyBatch.cmd /LOG+:c:\MyLog.txt
        ///SilentCMD c:\MyBatch.cmd /DELAY:3600 /LOG+:c:\MyLog.txt
        ///
        ///Version {0}
        ///Free software under MI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
    }
}
